package com.tssss.bysj.contract;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;

import com.tssss.bysj.R;
import com.tssss.bysj.application.ActivityManager;
import com.tssss.bysj.application.MyApplication;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;


public abstract class BaseActivity extends AppCompatActivity implements View,
        android.view.View.OnClickListener {

    private ImageButton mLeftBtn, mRightBtn;
    private ImageView mCenterIv;

    private PresenterImp mPresenter;
    private ActivityManager mActivityManager;
    private MyApplication mApplication;
    private Context mContext;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        mContext = this;
        setContentView(getLayoutId());
        findViews();

        // attach mPresenter
        if (attachPresenter() != null) {
            mPresenter = attachPresenter();
            mPresenter.attachView(this);
        }

        getActivityManager().addActivityInstance(this);
    }

    @Override
    protected void onStart() {
        super.onStart();
        setEventListeners();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        if (mPresenter != null) {
            mPresenter.detachView();
        }
    }

    /**
     * Subclass selects specific Presenter (extends PresenterImp)
     *
     * @return mPresenter
     */
    protected PresenterImp attachPresenter() {
        return null;
    }

    /**
     * Lock back key
     */
    @Override
    public void onBackPressed() {
    }

    /**
     * Handle the top bar click events uniformly.
     * <p>If you override this method, be sure that call {@code super.onClick().}</p>
     */
    @Override
    public void onClick(android.view.View v) {
        switch (v.getId()) {
            case R.id.top_bar_left:
                clickLeft();
                break;
            case R.id.top_bar_center:
                clickCenter();
                break;
            case R.id.top_bar_right:
                clickRight();
                break;
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        LinearLayout root = new LinearLayout(this);
        root.setBackgroundResource(getBackgroundResId());
        root.setOrientation(LinearLayout.VERTICAL);
        root.setLayoutParams(new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));

        ViewGroup viewGroup = findViewById(android.R.id.content);
        viewGroup.removeAllViews();
        viewGroup.addView(root);

        if (!isFullScreen()) {
            getLayoutInflater().inflate(getTopBarId(), root, true);
            setTopBar();
        }

        getLayoutInflater().inflate(layoutResID, root, true);
    }

    /**
     * Set background
     *
     * @return resId
     */
    protected int getBackgroundResId() {
        return R.drawable.bg_common;
    }

    /**
     * Set top bar
     */
    protected int getTopBarId() {
        return R.layout.top_bar;
    }

    /**
     * Set src of the left ImageButton
     */
    protected int getLeftBtnStyle() {
        return R.drawable.ic_btn_back;
    }

    /**
     * Set src of the center ImageView (title of current activity)
     */
    protected int getCenterIvStyle() {
        return 0;
    }

    /**
     * Set src of the right ImageButton
     */
    protected int getRightIbStyle() {
        return 0;
    }

    /**
     * Set activity to full screen
     */
    protected boolean isFullScreen() {
        return false;
    }

    /**
     * FindViewById()
     */
    protected abstract void findViews();

    /**
     * SetXXListener
     */
    protected abstract void setEventListeners();

    /**
     * Set layout id
     */
    protected abstract int getLayoutId();

    /**
     * Open activity without data
     */
    protected void openActivity(Class clazz) {
        Intent intent = new Intent(this, clazz);
        startActivity(intent);
    }

    /**
     * Initialize views of top bar.
     */
    private void setTopBar() {
        mLeftBtn = findViewById(R.id.top_bar_left);
        mCenterIv = findViewById(R.id.top_bar_center);
        mRightBtn = findViewById(R.id.top_bar_right);

        mLeftBtn.setOnClickListener(this);
        mCenterIv.setOnClickListener(this);
        mRightBtn.setOnClickListener(this);

        mLeftBtn.setImageResource(getLeftBtnStyle());
        mCenterIv.setImageResource(getCenterIvStyle());
        mRightBtn.setImageResource(getRightIbStyle());
    }

    /**
     * Handle event generated by the user clicking the left
     * view of top bar, the default is back.
     */
    protected void clickLeft() {
        this.finish();
    }

    /**
     * Handle event generated by the user clicking the center
     * view of top bar.
     */
    protected void clickCenter() {
    }

    /**
     * Handle event generated by the user clicking the right
     * view of top bar.
     */
    protected void clickRight() {
    }

    /**
     * Return mActivityManager.
     */
    protected ActivityManager getActivityManager() {
        if (mActivityManager == null) {
            mActivityManager = ActivityManager.getActivityManager();
        }

        return mActivityManager;
    }

    /**
     * Return mMyApplication.
     */
    protected MyApplication getMyApplication() {
        if (mApplication == null) {
            mApplication = MyApplication.getMyApplication();
        }

        return mApplication;
    }

    /**
     * Get context of current activity.
     */
    protected Context getContext() {
        if (mContext != null)
            return mContext;

        return getApplicationContext();
    }
}
